### ISSUE TITLE
Possible typo in the 2.1 install document

### ISSUE THREAD

**Issue by veidt** [gitlabhq/gitlab-ci#131]
It says to checkout 2-0-stable, when you are trying to install 2-1-stable.  Same with master.

**Comment by jvanbaarsen** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
