### ISSUE TITLE
Build log output cuts off after 65535 bytes

### ISSUE THREAD

**Issue by alexwhittemore** [gitlabhq/gitlab-ci#145]
I have a build script that makes a python virtualenv to test in. I'm trying to decrease its verbosity, but currently it's spewing lots of lines from some manual library installs, and it seems that everything after 65535 characters gets lopped off. The live update view works great, but as soon as success is reported, the actual test results get cut off.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
