### ISSUE TITLE
background jobs not working - sidekiq assets mysteriously missing

### ISSUE THREAD

**Issue by Hesse** [gitlabhq/gitlab-ci#294]
Here's my issue: I'm running CI 2-2-stable, when you click on background jobs it brings you to the dashboard page but the dashboard doesn't load with any of the styles or functionality. Then if you click anything, you're automatically logged out again. 

If you look at the console you notice that none of the sidekiq assets are loading. The strange part is, this seems to be an off/on issue. 

Now my build queue is out of whack and when I click something to run a build, it will build something else. 

See shots below. Any help would be appreciated. 

![screen shot 2013-10-08 at 11 06 14 am](https://f.cloud.github.com/assets/335354/1290115/d87f455e-302b-11e3-834d-d990674f6a82.png)
![screen shot 2013-10-08 at 11 11 53 am](https://f.cloud.github.com/assets/335354/1290134/0ef613d8-302c-11e3-9a1b-a09e6883cd47.png)

The above assets that are not loading are not to be found where they are said to be found:
/ext/sidekiq/stylesheets/bootstrap.css
ext/sidekiq/stylesheets/application.css 
ext/sidekiq/javascripts/application.js

**Comment by jvanbaarsen** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
