### ISSUE TITLE
Can't update the system environment from gitlab-CI

### ISSUE THREAD

**Issue by markshao** [gitlabhq/gitlab-ci#343]
My environment is ubuntu12.04 + gitlab-CI

I have manually set the JAVA_HOME and add it to the PATH. The following is the PATH value I print on the ubuntu console

/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/gitlab_ci_runner/jdk1.7.0_45/bin:/home/gitlab_ci_runner/apache/apache-maven-3.1.1/bin:/home/gitlab_ci_runner/apache/apache-maven-3.1.1/bin:/home/gitlab_ci_runner/jdk1.7.0_45/bin

But when I working on the gitlab-ci build, I always get the error that the JAVA_HOME is not set . And I print the PATH in the build script , found that the PATH value is not what I have previously set

/usr/local/lib/ruby/gems/2.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Who can help me

**Comment by jvanbaarsen** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
