### ISSUE TITLE
undefined method `is_admin'

### ISSUE THREAD

**Issue by unibyte** [gitlabhq/gitlab-ci#350]
Completed 302 Found in 1264ms (ActiveRecord: 0.3ms)
Started GET "/" for 127.0.0.1 at 2013-12-28 06:51:24 +0000
Processing by ProjectsController#index as HTML
  Rendered projects/index.html.haml within layouts/application (1.1ms)
  Rendered layouts/_head.html.haml (2.3ms)
  Rendered layouts/_nav.html.haml (1.7ms)
Completed 500 Internal Server Error in 10ms
~~~
ActionView::Template::Error (undefined method `is_admin' for #<User:0xb6d3444>):
    3:     .container-fluid
    4:       = link_to 'GitLab CI', root_path, class: "brand"
    5:       %ul.nav
    6:         - if current_user && current_user.is_admin
    7:           %li
    8:             = link_to admin_runners_path do
    9:               Runners
  app/models/user.rb:19:in `method_missing'
  app/views/layouts/_nav.html.haml:6:in `_app_views_layouts__nav_html_haml__380777673_87218810'
  app/views/layouts/application.html.haml:5:in `_app_views_layouts_application_html_haml___160073160_97920490'
~~~

**Comment by jvanbaarsen** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
