### ISSUE TITLE
relative_url_root in application.yml does not work

### ISSUE THREAD

**Issue by saily** [gitlabhq/gitlab-ci#398]
#### Issue:

Setting ``relative_url_root`` in ``config/applicaton.yml`` file has no effect. 

#### Workaround:

Set environment variable in following script which is used by default init script.
```
$ cat /etc/default/gitlab-ci
export RAILS_RELATIVE_URL_ROOT="/ci/"
```

**Comment by jvanbaarsen** [comment]
@saily This turns out not really a bug, more a not well-documented feature.

In order to support relative URL's you need to change it in a few places:
1) In config/application.rb add `config.relative_url_root = "/your_path"`
2) In your gitlab.yml file: relative_url_root: "/your_path"
3) In your unicorn.rb: ENV['RAILS_RELATIVE_URL_ROOT'] = "/your_path"

In the upcoming days, I'll look into documenting this a little better. I hope this can help you in the meanwhile.

**Comment by saily** [comment]
@jvanbaarsen you're right, gitlab_ci is working fine in subpath here. ping me if you need more info or help on documentation.
