### ISSUE TITLE
Retrieve runner registration tokens using a shell command

### ISSUE THREAD

**Issue by vincentdoba** [gitlabhq/gitlab-ci#429]
# Summary

Currently, to retrieve registration tokens used by runners, you need to connect to gitlab-ci web interface. It would be nice to retrieve registration token directly on shell using command line.

# Step to reproduce
- go to gitlab-ci install directory
- `grep -R REGISTRATION_TOKEN *` (where REGISTRATION_TOKEN is the registration token you get on the web interface)
- the token is not found

# Expected behavior
To have a command to retrieve runner next registration token, in order to be able to automate runners installation process and be able to use configuration management tools such as puppet, chef or ansible to install gitlab-ci and gitlab-ci-runners.

# Relevant logs and/or screenshots:
Token seems to be generated in _config/initializers/2_app.rb_, at line 4 : 

    RUNNERS_TOKEN = SecureRandom.hex(10)

# Possible fixes
- When generating token, save it on a file that can be greped.
- Add a command to retrieve token

**Comment by earsdown** [comment]
+1 for this.

**Comment by juhoojala** [comment]
+1 for this

**Comment by dgarros** [comment]
Hi 
I have exactly the same need
Is it possible in the latest release to retrieve the registration token programmatically ?
Thanks
Damien

**Comment by trusch** [comment]
+1 please fix this

**Comment by axilleas** [comment]
This project is deprecated, please use https://gitlab.com/gitlab-org/gitlab-ci-multi-runner instead.

**Comment by sammcj** [comment]
gitlab.com is sooooooooo slow since moving it to Azure though @axilleas - it was fine before that but now, loading https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/new?issue%5Bassignee_id%5D=&issue%5Bmilestone_id%5D= to create a new issue for this took 30 seconds!

Azure's disk IO performance so incredibly bad it's not really surprising, just like AWS everyone is having to employe people to build tools to work around their MITM oh sorry, I meant 'cloud''s problems.

![there is no cloud](https://cloud.githubusercontent.com/assets/862951/18871809/6eef0bca-84fa-11e6-9e22-3a3859826012.png)

Seriously though, it's such a put off for logging bugs and its not Gitlab's (as a product) fault - it's the platform underneath.

But yes I do understand Microsoft's dirty little lock-in / advertising trick of giving free cloud monies for ycombinator backed projects - still though, Azure isn't trustworth (unless you like SHA-1's issues by bluecoat oh I mean Symantec, oh I mean Blue Coat... oh I mean... you get the point.

**Comment by sammcj** [comment]
created again on gitlab's bug tracker: https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/1727

**Comment by axilleas** [comment]
Lol, thank you @vincentdoba :heart:
