### ISSUE TITLE
colorize build trace output based on predefined regex expressions

### ISSUE THREAD

**Issue by ssbarnea** [gitlabhq/gitlab-ci#607]
It would be extremely helpful if gitlab could colorize the console output based on a set of regular expressions, so that we could make colors red, warnings orange, make debug lines dimmed, ...

While some people may want to be able to overwrite these from the `.gitlab-ci.yaml` file, this feature should be under the control of the the instance, where admins could define new regular expressions.

A good example of similar feature is implemented into the famous OS X terminal: iTerm2 and here is an example:

![screenshot 2015-06-30 13 23 57](https://cloud.githubusercontent.com/assets/102495/8430702/4af0f502-1f2b-11e5-9073-209d39e6acbf.png)

**Comment by ayufan** [comment]
It's better to have tools that output colorised output instead.

**Comment by blaggacao** [comment]
+1

**Comment by kingsimba** [comment]
+1
Love it!

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
